from selenium import webdriver
import time
import os.path
from selenium.webdriver.support.ui import Select


file_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'duck_pic.png')
browser = webdriver.Chrome()
browser.get("http://localhost:8081/litecard/public_html/admin/login.php")
usr_name_field = browser.find_element_by_name("username")
usr_name_field.send_keys('admin')
paswd_field = browser.find_element_by_name("password")
paswd_field.send_keys('admin')
button_login = browser.find_element_by_tag_name('button')
button_login.click()
browser.find_elements_by_css_selector('#app-')[1].click()
products_list = browser.find_elements_by_css_selector('.row')
browser.find_elements_by_css_selector('.button')[1].click()
folder = browser.find_elements_by_css_selector('#content li a')
browser.find_element_by_css_selector('label:nth-child(3) input[value="1"]').click()
browser.find_element_by_name('name[en]').send_keys("new Duck")
browser.find_element_by_name('code').send_keys("code")
browser.find_element_by_css_selector('[data-name = "Rubber Ducks"]').click()
browser.find_element_by_name('product_groups[]').click()
browser.find_element_by_name('quantity').send_keys('15')
browser.find_element_by_css_selector('[type="file"]').send_keys(file_path)
time.sleep(2)
browser.find_element_by_name('date_valid_from').send_keys('10-10-2019')
browser.find_element_by_name('date_valid_to').send_keys('10-12-2019')
folder[1].click()
time.sleep(2)
Select(browser.find_element_by_name('manufacturer_id')).select_by_value('1')
browser.find_element_by_name('keywords').send_keys('angry duck')
browser.find_element_by_name('short_description[en]').send_keys('Duck')
browser.find_element_by_css_selector('.trumbowyg-editor').send_keys('Duck')
browser.find_element_by_name('head_title[en]').send_keys('Angry Duck')
browser.find_element_by_name('meta_description[en]').send_keys('Angry Duck')
folder[3].click()
time.sleep(2)
browser.find_element_by_name('purchase_price').send_keys('8')
Select(browser.find_element_by_name('purchase_price_currency_code')).select_by_value('EUR')
browser.find_element_by_name('prices[USD]').send_keys('70')
browser.find_element_by_name('prices[EUR]').send_keys('80')
browser.find_element_by_name('save').click()
poducts_list2 = browser.find_elements_by_css_selector('.row')
time.sleep(2)
if len(poducts_list2)==len(products_list)+1:
    print("Correct")
else:
    print("Error")
